# Generated by Django 6.0.2 on 2026-03-02 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('architecture', models.CharField(choices=[('text', 'Text / LLM'), ('vision', 'Vision / CNN / ViT'), ('graph', 'Graph Neural Network'), ('diffusion', 'Diffusion / Generative'), ('other', 'Other')], max_length=50)),
                ('github_url', models.URLField(blank=True, help_text='Link to the source code repository', null=True)),
                ('paper_url', models.URLField(blank=True, help_text='Link to the associated research paper', null=True)),
                ('huggingface_url', models.URLField(blank=True, help_text='Link to HuggingFace or model weights', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('tutorial', 'Tutorial / Guide'), ('notebook', 'Jupyter Notebook'), ('dataset', 'Training Dataset Link')], max_length=50)),
                ('content', models.TextField(help_text='Markdown content or brief description')),
                ('external_link', models.URLField(blank=True, null=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='ai_hub.aimodel')),
            ],
        ),
    ]
