# Generated by Django 6.0.2 on 2026-03-02 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(help_text='Comma-separated authors', max_length=500)),
                ('abstract', models.TextField()),
                ('field', models.CharField(choices=[('bioinformatics', 'Bioinformatics'), ('systems_biology', 'Systems Biology'), ('genomics', 'Genomics & Epigenomics'), ('proteomics', 'Proteomics'), ('clinical', 'Clinical Informatics')], max_length=50)),
                ('pdf_file', models.FileField(upload_to='research_papers/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('doi', models.CharField(blank=True, help_text='Digital Object Identifier', max_length=100, null=True)),
                ('read_count', models.IntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
